08.ASP.NET-Core/CodeExamplesFromLectures/CodeExamplesFromLectures/ViewModels/Tests/CandidateType.cs
namespace CodeExamplesFromLectures.ViewModels.Tests
{
    public enum CandidateType
    {
        None = 0, 
        Qa = 1,
        Progamer = 2,
        SeniorDeveloper = 3,

    }
}

08.ASP.NET-Core/CodeExamplesFromLectures/CodeExamplesFromLectures/ViewModels/Tests/Name.cs
using CodeExamplesFromLectures.ModelValidationAttributes;
using System.ComponentModel.DataAnnotations;

namespace CodeExamplesFromLectures.ViewModels.Tests
{
    public class Name
    {
        [Required]
        [NameValidation]
        public string FirstName { get; set; }

        [Required]
        [NameValidation]
        public string LastName { get; set; }
    }
}

08.ASP.NET-Core/CodeExamplesFromLectures/CodeExamplesFromLectures/ViewModels/Tests/TestsInputModel.cs
using CodeExamplesFromLectures.ModelBinders;
using CodeExamplesFromLectures.ModelValidationAttributes;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CodeExamplesFromLectures.ViewModels.Tests
{
    public class TestsInputModel : IValidatableObject
    {
        //public int Id { get; set; }

        //[ModelBinder(typeof(YearModelBinder))]
        //public int Year { get; set; }

        //[Range(2000, int.MaxValue)]
        //public int[] Years { get; set; }


        public Name Name { get; set; }

        [DataType(DataType.Date)]
        [IsBefore("01/01/2000")]
        public DateTime DateOfBirth { get; set; }

        [Required]
        [NameValidation]
        public string University { get; set; }

        [EmailAddress]// use always with required
        [Required]
        public string Email { get; set; }

        [Required]
        [StringLength(10, MinimumLength = 10, ErrorMessage = "Must be 10 digits")]
        public string EGN { get; set; }

        [Display(Name = "Years of experience")]
        public int YearsOfExperience { get; set; }

        public CandidateType CandidateType { get; set; }

        public IEnumerable<SelectListItem> AllCandidateTypes { get; set; }

        public IFormFileCollection CV { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (int.Parse(this.EGN.Substring(0, 2)) != this.DateOfBirth.Year % 100)
            {
                yield return new ValidationResult("Year of birth and EGN not matching");
            }
        }
    }
}

08.ASP.NET-Core/CodeExamplesFromLectures/CodeExamplesFromLectures/Controllers/TestsController.cs
using CodeExamplesFromLectures.Services;
using CodeExamplesFromLectures.ViewModels.Tests;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.FileProviders;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace CodeExamplesFromLectures.Controllers
{
    public class TestsController : Controller
    {
        private readonly IWebHostEnvironment env;
        private readonly IConfiguration config;
        private readonly IPositionService positionService;
        private IYearsService yearsService;

        public TestsController(IYearsService yearsService, IWebHostEnvironment env, IConfiguration config, IPositionService positionService)
        {
            this.yearsService = yearsService;
            this.env = env;
            this.config = config;
            this.positionService = positionService;
        }

        //public IActionResult Index(int id)// if not put int = 0
        //{
        //    return this.Json(id);
        //}

        //public IActionResult Index([FromBody]TestsInputModel input, [FromHeader] string accept, [FromQuery] int id)// localhost:5001/Test/Index?Id=1&Years=2020&Years=2019&Name.FirstName=Marin&Name.Lastname=Balashkov // [FromBody] serialize to JSON
        //{
        //    if (!this.ModelState.IsValid)
        //    {
        //        return this.Json(this.ModelState);
        //    }
        //    return this.Json(input);
        //}



        [HttpGet]
        public IActionResult Index()
        {
            var model = new TestsInputModel()
            {

                University = "SoftUni",//defaul value
                
                AllCandidateTypes = this.positionService.GetAll()// Get enum from DB

            };

            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Index(TestsInputModel input)
        {
            if (input.CandidateType < 0)// throw error from controller
            {
                this.ModelState.AddModelError(nameof(TestsInputModel.CandidateType), "Custom Error Message");
            }

            if (!this.ModelState.IsValid)
            {
                input.AllCandidateTypes = this.positionService.GetAll();
                return this.View(input);//populate data in forms after error
            }

            using (var fileStream = new FileStream(@"C:\Temp\User.pdf", FileMode.Create))
            {
                var expectedFileExt = new[] { ".pdf", ".doc", ".docx" };

                if (expectedFileExt.Any(x => input.CV.First().FileName.EndsWith(x)))
                {

                    if (input.CV.First().Length > 1024 * 1024 * 10)//check the file size
                    {
                        this.ModelState.AddModelError(nameof(TestsInputModel.CV), "фаила е по гола м от 10 мб.");
                    }
                    await input.CV.First().CopyToAsync(fileStream);

                }


            }

            return this.Redirect("/");

        }

        public IActionResult Download(string fileName)
        {
            // Construct the path to the physical files folder
            string filePath = this.env.ContentRootPath + this.config["FileSystem:FilesFolderPath"];

            IFileProvider provider = new PhysicalFileProvider(filePath); // Initialize the Provider
            IFileInfo fileInfo = provider.GetFileInfo(fileName); // Extract the FileInfo

            var readStream = fileInfo.CreateReadStream(); // Extact the Stream
            var mimeType = "application/octet-stream"; // Set a mimeType

            return File(readStream, mimeType, fileName); // Return FileResult
        } // NOTE: There is no check if the File exists. This action may result in an error
        private static string MakeValidFileName(string name)
        {
            string invalidChars = System.Text.RegularExpressions.Regex.Escape(new string(System.IO.Path.GetInvalidFileNameChars()));
            string invalidRegStr = string.Format(@"([{0}]*\.+$)|([{0}]+)", invalidChars);

            return System.Text.RegularExpressions.Regex.Replace(name, invalidRegStr, "_");
        }
    }
}

08.ASP.NET-Core/CodeExamplesFromLectures/CodeExamplesFromLectures/Views/Tests/Index.cshtml
@using CodeExamplesFromLectures.ViewModels.Tests
@model TestsInputModel
<h1>Candiate for Junior Software Developer</h1>

<form class="form" method="post" asp-controller="Tests" asp-action="Index" enctype="multipart/form-data"> @*enctype must be added for files*@


    <div asp-validation-summary="All"></div>

    <div class=form-group>
        <label asp-for=Name.FirstName></label>
        <input asp-for="Name.FirstName" class="form-control" />
        <span asp-validation-for=Name.FirstName class="text-danger"></span>
    </div>



    <div class=form-group>
        <label asp-for=Name.LastName></label>
        <input asp-for="Name.LastName" class="form-control" />
        <span asp-validation-for=Name.LastName class="text-danger"></span>
    </div>



    <div class=form-group>
        <label asp-for=EGN></label>
        <input asp-for=EGN class="form-control" />
        <span asp-validation-for=EGN class="text-danger"></span>
    </div>



    <div class=form-group>
        <label asp-for=Email></label>
        <input asp-for=Email class="form-control" />
        <span asp-validation-for=Email class="text-danger"></span>
    </div>



    <div class=form-group>
        <label asp-for=University></label>
        <input asp-for=University class="form-control" />
        <span asp-validation-for=University class="text-danger"></span>
    </div>



    <div class=form-group>
        <label asp-for=YearsOfExperience></label>
        <input asp-for=YearsOfExperience class="form-control" />
        <span asp-validation-for=YearsOfExperience class="text-danger"></span>
    </div>




    <div class=form-group>
        <label asp-for=CandidateType></label>
        <select class="form-control" asp-for=CandidateType asp-items=@Html.GetEnumSelectList(typeof(CandidateType))></select>
        <span asp-validation-for=CandidateType class="text-danger"></span>
    </div>

    <div class=form-group>
        <label asp-for=DateOfBirth></label>
        <input asp-for=DateOfBirth class="form-control" />
        <span asp-validation-for=DateOfBirth class="text-danger"></span>
    </div>

    <div class=form-group>
        <label asp-for=AllCandidateTypes></label>
        <select class="form-control" asp-for=AllCandidateTypes asp-items=@Model.AllCandidateTypes></select>
        <span asp-validation-for=CandidateType class="text-danger"></span>
    </div>

        <div class=form-group>
        <label asp-for=CV></label>
        <input asp-for=CV class="form-control" />
        <span asp-validation-for=CV class="text-danger"></span>
    </div>

    <hr />

    <input type="submit" value="Candidate" class="btn btn-primary" />
</form>

@section Scripts {
<partial name="_ValidationScriptsPartial" />
}